---
- name: create user
  hosts: all
  remote_user: vagrant
  become: true
  tasks:
  - name: Create a group
    group:
     name: admin
     state: present
     system: yes

  - name: Create 5 users
    user:
     name: "{{ item }}"
     create_home: yes
     shell: /bin/bash
     group: admin
     append: yes
     state: present
     generate_ssh_key: yes
     ssh_key_bits: 2048
     ssh_key_file: .ssh/id_rsa
     password: xyz
    with_items:
     - User1
     - User2
     - User3
     - User4
     - User5

  - name: Create a new directory
    file:
     path: /home/vagrant/ninja
     state: directory
     group: admin
     owner: root
     mode: 0755
...
