
---
  - name: Rotate_keys
    hosts: app
    become: true
    become_user: root
    gather_facts: true
    tasks:
     - name: Set authorized key took from file
       authorized_key:
        user: root
        state: present
        exclusive: True
        key: "{{ lookup('file', '/home/sudipt/.ssh/id_rsa1.pub') }}"
...
